from django.shortcuts import render
from django.http import HttpResponse
from databaseManager.models import Recipe
from databaseManager.forms import RecipeForm
import requests
import json
from django.utils import timezone
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth import logout

#list of example recipes to be displayed at bottom of home page- could change/add more detail in future
recipes = [
  {
    'author': 'Generated by: Harold',
    'title': 'Recipe: Meatballs',
    'ingredients': 'Ingredients inputted: meat in ball shape, salt, oil',
    'date_posted': 'Date Posted: April 18th, 2024'
  },
  {
    'author': 'Generated by: Bodybuilder Brad',
    'title': 'Recipe: Pb & J',
    'ingredients': 'Ingredients inputted: peanut butter, jelly, bread, Trenbolone',
    'date_posted': 'Date Posted: May 24th, 2022'
  },
  {
    'author': 'Generated by: Yukon Cornelius',
    'title': 'Recipe: Lollipop',
    'ingredients': 'Ingredients inputted: icicle, peppermint',
    'date_posted': 'Date Posted: January 2nd, 1964'
  }
]

# Create your views here.

def generate_recipe_chatGPT(ingredients):
    try:
        # ChatGPT API endpoint
        api_endpoint = 'https://api.openapi.com/v1/completions'

        # Provide OpenAI API key
        api_key = 'sk-proj-gMhE1JpO8HsUAB32TSCeT3BlbkFJ4kSrObVWHekv9TpdiAp8'

        # Request headers
        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}',
        }

        # Request data
        data = {
            'model': 'text-davinci-003', # check what model 
            'prompt': f'Generate a recipe using the following ingredients: {ingredients}',
            'max_tokens':100, # adjust
        }

        # Make POST request to ChatGPT API
        response = requests.post(api_endpoint, headers=headers, data=json.dumps(data))

        # Check if request was successful
        if response.status_code == 200:
            # Extract generated recipe from response
            generated_recipe_text = response.json()['choices'][0]['text']

            # Construct recipe dictionary
            generated_recipe = {
                'author': 'Generated Author',
                'title': 'Generated Recipe',  # Default title if not provided by API
                'description': generated_recipe_text,
                'ingredients': ingredients,
                'date_posted': 'Today'
            }

            # Return generated recipe
            return generated_recipe
        else:
            # If request failed, return error message
            return {
                'error': f'Failed to generate recipe. API responded with status code {response.status_code}.'
            }
    except Exception as e:
        # If an exception occurs, return error message
        return {
            'error': f'Failed to generate recipe. An exception occurred: {str(e)}'
        }


#function to save recipe to user account in postgreSQL database
def save_recipe(title, description, ingredients, author):
    recipe = Recipe(
        title=title,
        description=description,
        ingredients=ingredients,
        author=author  # add recipe to user account
    )
    recipe.save() #save recipe to database using method from databaseManager
    
    

from django.contrib.auth.decorators import login_required

@login_required(login_url='/login/')  # This decorator ensures that only logged-in users can access this view
def home(request):
    if request.method == 'POST':
        # Handle submitted recipe
        form = RecipeForm(request.POST)
        if form.is_valid():
            # Generate recipe with GPT
            generated_recipe = generate_recipe_chatGPT(form.cleaned_data['ingredients'])

            # Check if the generated recipe is not empty
            if generated_recipe:
                # Print the generated recipe for debugging
                print("Generated Recipe:", generated_recipe)

                # Create a new instance of the Recipe model with the generated recipe
                if request.user.is_authenticated:
                    # If the user is logged in, set the author to the logged-in user
                    recipe = Recipe(
                        title="Generated Recipe",
                        description=generated_recipe,
                        ingredients=form.cleaned_data['ingredients'],
                        author=request.user
                    )
                else:
                    # If the user is not logged in, set the author to None
                    recipe = Recipe(
                        title="Generated Recipe",
                        description=generated_recipe,
                        ingredients=form.cleaned_data['ingredients'],
                        author=None
                    )
                # Save the new recipe to the database
                recipe.save()

                # Redirect to a success page or render a success message
                return render(request, 'pages/success.html',{'recipe': recipe})
            else:
                # If the generated recipe is empty, display an error message
                error_message = 'Failed to generate recipe. Please try again later.'
                print("Error Message:", error_message)  # Debugging print statement
                return render(request, 'pages/error.html', {'error_message': error_message})
        
    else:
        form = RecipeForm()
        
    context = {
        'form': form,
        'recipes': recipes,
    }
    return render(request, 'pages/home.html', context)

def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to login page after successful registration
    else:
        form = RegistrationForm()
    return render(request, 'registration/registration.html', {'form': form})

def login_page(request):
    # Render the login page template
    return render(request, 'pages/login.html')


def logout_view(request):
    logout(request)
    return redirect('home')  # Redirect to the home page after logout

