from django.http import HttpResponse
from databaseManager.models import Recipe
from databaseManager.forms import RecipeForm
import json
from django.conf import settings
from django.utils import timezone
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth import logout

#list of example recipes to be displayed at bottom of home page- could change/add more detail in future
recipes = [
  {
    'author': 'Generated by: Harold',
    'title': 'Recipe: Meatballs',
    'ingredients': 'Ingredients inputted: meat in ball shape, salt, oil',
    'date_posted': 'Date Posted: April 18th, 2024'
  },
  {
    'author': 'Generated by: Bodybuilder Brad',
    'title': 'Recipe: Pb & J',
    'ingredients': 'Ingredients inputted: peanut butter, jelly, bread, Trenbolone',
    'date_posted': 'Date Posted: May 24th, 2022'
  },
  {
    'author': 'Generated by: Yukon Cornelius',
    'title': 'Recipe: Lollipop',
    'ingredients': 'Ingredients inputted: icicle, peppermint',
    'date_posted': 'Date Posted: January 2nd, 1964'
  }
]

# Create your views here.
import re
import json
from openai import OpenAI
import openai

#sets the tone: funny, but the recipe still has to be cookable
SYSTEM_PROMPT = (
    "You are a playful, slightly unhinged chef with a great sense of humor. "
    "Whatever ingredients you're given, even ridiculous ones, commit to them and write a real, cookable recipe. "
    "Give it a funny, creative title and a witty description, and keep the steps practical."
)

#asks for a JSON object so the title, description, and steps come back as separate fields instead of free text to parse
def build_recipe_prompt(ingredients):
    return (
        f"Create a recipe using these ingredients: {ingredients}.\n"
        "Reply with only a JSON object with these keys:\n"
        '"title": a short, funny recipe name (under 80 characters)\n'
        '"description": one or two witty sentences about the dish\n'
        '"instructions": a list of steps in order, each step a plain string'
    )

#send the request; JSON mode guarantees valid JSON, but if the model doesn't support it, retry without it
def request_recipe(client, ingredients):
    kwargs = dict(
        #model is set by the OPENAI_MODEL environment variable so it can change without a code change
        model=settings.OPENAI_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": build_recipe_prompt(ingredients)},
        ],
        #caps cost per recipe; newer models spend part of this on internal reasoning before writing,
        #so it needs plenty of headroom or the reply comes back empty
        max_completion_tokens=4000,
    )
    try:
        return client.chat.completions.create(response_format={"type": "json_object"}, **kwargs)
    except openai.BadRequestError as e:
        print(f"JSON mode not accepted, retrying without it: {e}")
        return client.chat.completions.create(**kwargs)

#strip markdown formatting (**bold**, # headings, list bullets) so leftover symbols don't end up in the recipe
def strip_markdown(text):
    text = re.sub(r"[*_`]+", "", text)
    text = re.sub(r"^\s*#+\s*", "", text, flags=re.MULTILINE)
    return text.strip()

#turn the model's reply into title, description, and numbered instructions
#tries JSON first; falls back to finding "Title / Description / Instructions" labels in plain or markdown text
def parse_recipe(content):
    title = "Generated Recipe"
    description = "A creative recipe generated by ChatGPT."
    instructions = "No instructions provided."

    data = None
    start, end = content.find("{"), content.rfind("}")
    if start != -1 and end > start:
        try:
            data = json.loads(content[start:end + 1])
        except json.JSONDecodeError:
            data = None

    if isinstance(data, dict):
        title = strip_markdown(str(data.get("title") or title))
        description = strip_markdown(str(data.get("description") or description))
        steps = data.get("instructions")
        if isinstance(steps, list) and steps:
            #number the steps, dropping any numbering the model already added
            cleaned = [re.sub(r"^\s*\d+[.)]\s*", "", strip_markdown(str(step))) for step in steps if str(step).strip()]
            instructions = "\n".join(f"{i}. {step}" for i, step in enumerate(cleaned, 1))
        elif steps:
            instructions = strip_markdown(str(steps))
    else:
        text = strip_markdown(content)
        # Extract title (label optional: otherwise the first line is the title)
        title_match = re.search(r"(?im)^\s*title\s*:?\s*(.+)$", text)
        if title_match:
            title = title_match.group(1).strip()
        elif text:
            title = text.splitlines()[0].strip()
        # Extract description
        description_match = re.search(r"(?is)description\s*:?\s*(.+?)(?:\n\s*\n|\n\s*(?:ingredients|instructions)\b)", text)
        if description_match:
            description = description_match.group(1).strip()
        # Extract instructions (everything after the label)
        instructions_match = re.search(r"(?is)instructions\s*:?\s*\n?(.+)", text)
        if instructions_match:
            instructions = instructions_match.group(1).strip()

    #the database title column holds 100 characters
    return title[:100], description, instructions

def generate_recipe_chatGPT(ingredients):
    try: 
        # Provide OpenAI API key
        client = OpenAI(api_key=settings.OPENAI_API_KEY)

        response = request_recipe(client, ingredients)

       # Extract the response message
        if response and response.choices and response.choices[0].message and response.choices[0].message.content:
            # Parse the response to find title, description, and instructions
            title, description, instructions = parse_recipe(response.choices[0].message.content)

            # Return the title, instructions, and current date
            return {
                "title": title,
                "description": description,
                "instructions": instructions,
                "date_created": timezone.now()
            }

        else:
            #log why the reply was empty (e.g. finish_reason "length" = ran out of tokens, or a refusal)
            choice = response.choices[0] if response and response.choices else None
            print("Error: No recipe text in response. finish_reason:",
                  getattr(choice, "finish_reason", None),
                  "refusal:", getattr(getattr(choice, "message", None), "refusal", None))
            return {
                "error": True,
                "title": "Error generating recipe.",
                "description": "Could not generate a recipe with the given ingredients.",
                "instructions": "Could not generate a recipe with the given ingredients.",
                "date_created": timezone.now()
            }

    except openai.AuthenticationError as e:
        print(f"Authentication Error: {e}")
        return {
            "error": True,
            "title": "Authentication error",
            "description": "Could not authenticate with the OpenAI API.",
            "instructions": "Please check your OpenAI API key.",
            "date_created": timezone.now()
        }

    except openai.RateLimitError as e:
        print(f"Rate Limit Error: {e}")
        return {
            "error": True,
            "title": "Quota exceeded",
            "description": "The API quota limit has been reached.",
            "instructions": "Please check your OpenAI plan and billing details.",
            "date_created": timezone.now()
        }

    except openai.BadRequestError as e:
        print(f"Invalid Request Error: {e}")
        return {
            "error": True,
            "title": "Invalid request error",
            "description": "Invalid request sent to the OpenAI API.",
            "instructions": "Please check the request data and try again.",
            "date_created": timezone.now()
        }

    except openai.APIConnectionError as e:
        print(f"API Connection Error: {e}")
        return {
            "error": True,
            "title": "API connection error",
            "description": "Could not connect to the OpenAI API.",
            "instructions": "Please check your network connection and try again.",
            "date_created": timezone.now()
        }

    except openai.APIError as e:
        print(f"API Error: {e}")
        return {
            "error": True,
            "title": "API error",
            "description": "An internal error occurred while generating the recipe.",
            "instructions": "Please try again later.",
            "date_created": timezone.now()
        }

    except Exception as e:
        print(f"Error generating recipe: {e}")
        return {
            "error": True,
            "title": "Error generating recipe.",
            "description": "An unexpected error occurred.",
            "instructions": "Please try again later.",
            "date_created": timezone.now()
        }


#function to save recipe to user account in postgreSQL database
def save_recipe(title, description, ingredients, author):
    recipe = Recipe(
        title=title,
        description=description,
        ingredients=ingredients,
        author=author  # add recipe to user account
    )
    recipe.save() #save recipe to database using method from databaseManager
    
    

from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')  # This decorator ensures that only logged-in users can access this view
def home(request):
    if request.method == 'POST':
        # Handle submitted recipe
        form = RecipeForm(request.POST)
        if form.is_valid():
            # Generate recipe with GPT
            ingredients = form.cleaned_data['ingredients']
            print("Ingredients for Recipe Generation:", ingredients)
            generated_recipe = generate_recipe_chatGPT(ingredients)

            # Check that generation worked (error results are marked with "error": True and never saved)
            if generated_recipe and not generated_recipe.get("error"):

                # Create a new instance of the Recipe model with the generated recipe
                    # If the user is logged in, set the author to the logged-in user
                recipe = Recipe(
                    title=generated_recipe['title'],
                    description=generated_recipe['description'],
                    ingredients=ingredients,
                    instructions=generated_recipe['instructions'],
                    author=request.user if request.user.is_authenticated else None,
                    date_created=generated_recipe['date_created']
                    )
                # Save the new recipe to the database
                recipe.save()
            
                # Redirect to a success page or render a success message
                return render(request, 'pages/success.html',{'recipe': recipe})
            else:
                # If generation failed, show the error page with the reason instead of saving it as a recipe
                error_message = 'Failed to generate recipe. Please try again later.'
                if generated_recipe:
                    error_message = f"{generated_recipe['title']}: {generated_recipe['description']}"
                print("Error Message:", error_message)  # Debugging print statement
                return render(request, 'pages/error.html', {'error_message': error_message})
        
    else:
        form = RecipeForm()
        
    context = {
        'form': form,
        'recipes': recipes,
    }
    return render(request, 'pages/home.html', context)



def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to login page after successful registration
    else:
        form = RegistrationForm()
    return render(request, 'registration/registration.html', {'form': form})

def login_page(request):
    # Render the login page template
    return render(request, 'pages/login.html')


def logout_view(request):
    logout(request)
    return redirect('home')  # Redirect to the home page after logout


@login_required(login_url='/login/')
def browse_recipes(request):
    recipes = Recipe.objects.all().order_by('-date_created')
    return render(request, 'pages/browse_recipes.html', {'recipes': recipes})


@login_required(login_url='/login/')
def my_recipes(request):
    recipes = Recipe.objects.filter(author=request.user).order_by('-date_created')
    return render(request, 'pages/my_recipes.html', {'recipes': recipes})

