from django.http import HttpResponse
from databaseManager.models import Recipe
from databaseManager.forms import RecipeForm
import requests
import json
from django.conf import settings
from django.utils import timezone
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegistrationForm
from django.contrib.auth import logout

#list of example recipes to be displayed at bottom of home page- could change/add more detail in future
recipes = [
  {
    'author': 'Generated by: Harold',
    'title': 'Recipe: Meatballs',
    'ingredients': 'Ingredients inputted: meat in ball shape, salt, oil',
    'date_posted': 'Date Posted: April 18th, 2024'
  },
  {
    'author': 'Generated by: Bodybuilder Brad',
    'title': 'Recipe: Pb & J',
    'ingredients': 'Ingredients inputted: peanut butter, jelly, bread, Trenbolone',
    'date_posted': 'Date Posted: May 24th, 2022'
  },
  {
    'author': 'Generated by: Yukon Cornelius',
    'title': 'Recipe: Lollipop',
    'ingredients': 'Ingredients inputted: icicle, peppermint',
    'date_posted': 'Date Posted: January 2nd, 1964'
  }
]

# Create your views here.
import openai
import re
def generate_recipe_chatGPT(ingredients):
    try: 
        # Provide OpenAI API key
        openai.api_key = settings.OPENAI_API_KEY

        # Debug print statement to verify API key is correctly set
        print("Using OpenAI API Key:", openai.api_key)

        response = openai.ChatCompletion.create(
            model = "gpt-3.5-turbo",
            messages = [
                {"role": "system", "content": "You are a helpful chef that generates creative recipes."},
                {"role": "user", "content": f"Generate a recipe using the following ingredients: {ingredients}."
                                            f"Include a title, description, and detailed instructions."}
            ],          
            max_tokens = 500, 
        )
     # Debug print statement for the response
        print("API Response:", response)

       # Extract the response message
        if response and response.choices and response.choices[0].message:
            # Extract and parse the content
            content = response.choices[0].message['content']
            print("Generated Recipe Content:", content)

            # Parse the response to find title, description, and instructions
            title = "Generated Recipe"
            description = "A creative recipe generated by ChatGPT."
            instructions = "No instructions provided."

            # Extract title
            title_match = re.search(r"(?i)(title:)(.*)", content)
            if title_match:
                title = title_match.group(2).strip()

            # Extract description
            description_match = re.search(r"(?i)(description:)(.*)", content)
            if description_match:
                description = description_match.group(2).strip()

            # Extract instructions
            instructions_match = re.search(r"(?i)(instructions:)(.*)", content, re.DOTALL)
            if instructions_match:
                instructions = instructions_match.group(2).strip()

            # Return the title, instructions, and current date
            return {
                "title": title,
                "description": description,
                "instructions": instructions,
                "date_created": timezone.now()
            }

        else:
            print("Error: No valid response message found")
            return {
                "title": "Error generating recipe.",
                "description": "Could not generate a recipe with the given ingredients.",
                "instructions": "Could not generate a recipe with the given ingredients.",
                "date_created": timezone.now()
            }

    except openai.error.AuthenticationError as e:
        print(f"Authentication Error: {e}")
        return {
            "title": "Authentication error",
            "description": "Could not authenticate with the OpenAI API.",
            "instructions": "Please check your OpenAI API key.",
            "date_created": timezone.now()
        }

    except openai.error.RateLimitError as e:
        print(f"Rate Limit Error: {e}")
        return {
            "title": "Quota exceeded",
            "description": "The API quota limit has been reached.",
            "instructions": "Please check your OpenAI plan and billing details.",
            "date_created": timezone.now()
        }

    except openai.error.InvalidRequestError as e:
        print(f"Invalid Request Error: {e}")
        return {
            "title": "Invalid request error",
            "description": "Invalid request sent to the OpenAI API.",
            "instructions": "Please check the request data and try again.",
            "date_created": timezone.now()
        }

    except openai.error.APIConnectionError as e:
        print(f"API Connection Error: {e}")
        return {
            "title": "API connection error",
            "description": "Could not connect to the OpenAI API.",
            "instructions": "Please check your network connection and try again.",
            "date_created": timezone.now()
        }

    except openai.error.APIError as e:
        print(f"API Error: {e}")
        return {
            "title": "API error",
            "description": "An internal error occurred while generating the recipe.",
            "instructions": "Please try again later.",
            "date_created": timezone.now()
        }

    except Exception as e:
        print(f"Error generating recipe: {e}")
        return {
            "title": "Error generating recipe.",
            "description": "An unexpected error occurred.",
            "instructions": "Please try again later.",
            "date_created": timezone.now()
        }




#function to save recipe to user account in postgreSQL database
def save_recipe(title, description, ingredients, author):
    recipe = Recipe(
        title=title,
        description=description,
        ingredients=ingredients,
        author=author  # add recipe to user account
    )
    recipe.save() #save recipe to database using method from databaseManager
    
    

from django.contrib.auth.decorators import login_required

from .views import generate_recipe_chatGPT

@login_required(login_url='/login/')  # This decorator ensures that only logged-in users can access this view
def home(request):
    if request.method == 'POST':
        # Handle submitted recipe
        form = RecipeForm(request.POST)
        if form.is_valid():
            # Generate recipe with GPT
            ingredients = form.cleaned_data['ingredients']
            print("Ingredients for Recipe Generation:", ingredients)
            generated_recipe = generate_recipe_chatGPT(ingredients)

            # Check if the generated recipe is not empty
            if generated_recipe and generated_recipe != "Error generating recipe.":
                # Print for debugging
                print("Generated Recipe:", generated_recipe)

                # Create a new instance of the Recipe model with the generated recipe
                    # If the user is logged in, set the author to the logged-in user
                recipe = Recipe(
                    title=generated_recipe['title'],
                    description=generated_recipe['description'],
                    ingredients=ingredients,
                    instructions=generated_recipe['instructions'],
                    author=request.user if request.user.is_authenticated else None,
                    date_created=generated_recipe['date_created']
                    )
                # Save the new recipe to the database
                recipe.save()
            
                # Redirect to a success page or render a success message
                return render(request, 'pages/success.html',{'recipe': recipe})
            else:
                # If the generated recipe is empty, display an error message
                error_message = 'Failed to generate recipe. Please try again later.'
                print("Error Message:", error_message)  # Debugging print statement
                return render(request, 'pages/error.html', {'error_message': error_message})
        
    else:
        form = RecipeForm()
        
    context = {
        'form': form,
        'recipes': recipes,
    }
    return render(request, 'pages/home.html', context)



def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to login page after successful registration
    else:
        form = RegistrationForm()
    return render(request, 'registration/registration.html', {'form': form})

def login_page(request):
    # Render the login page template
    return render(request, 'pages/login.html')


def logout_view(request):
    logout(request)
    return redirect('home')  # Redirect to the home page after logout

